version: "3.3"
services:
  app:
    build: .
    volumes:
      - type: bind
        source: /home/in-aas-alvma/bots_config/questionnaire_bot/config
#        source: /Users/amalinko/PythonProjects/QuestionnaireBot/config
        target: /QuestionnaireBot/config
      - type: bind
        source: /var/log/os-questionnaire-bot
#        source: /Users/amalinko/PythonProjects/QuestionnaireBot/logs
        target: /QuestionnaireBot/logs
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "9300:9300"