version: "3.3"
services:
  app:
    build: .
    volumes:
      - type: bind
        source: /home/ubuntu/bots_config/questionnaire_bot/config
#        source: /Users/amalinko/PythonProjects/QuestionnaireBot/config
        target: /QuestionnaireBot/config
      - type: bind
        source: /var/log/os-questionnaire-bot
#        source: /Users/amalinko/PythonProjects/QuestionnaireBot/logs
        target: /QuestionnaireBot/logs
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "9300:9300"
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
