platform:
  - en_name: "Example"
    ru_name: "Пример"
    services:
      - ris: "0000"
        mnemo: "ABCD"
        name: "Название сервиса"
        responsible_admins_id: [0, 1]
      - ris: "1111"
        mnemo: "DCBA"
        name: "Название еще одного сервиса"
        responsible_admins_id: [1, 2]
    users:
      - name: Пример Первый
        id: 0
        telegram_username: "@Example1"
      - name: Пример Второй
        id: 1
        telegram_username: "@exam_ple_2"
      - name: Пример Третий
        id: 2
        telegram_username: "@exam_ple3"
